- name: ec2instance-playbook
  hosts: host
  become_user: root
  become_method: sudo
  tasks:
    - name: update
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400
    - name: Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest
        update_cache: true

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true

    - name: Install Docker Module for Python
      pip:
        name: docker
    - name: Clone the git Repository
      git:
        repo: "{{git_repo}}"
        dest: /home/ubuntu/{{git_repo}}

    - name: cat env variables to file .env in source
      copy:
        content: {{env}}
        dest: /home/ubuntu/{{git_repo}}/.env
    - name: Run docker compose into the directory
      command: docker-compose up -d
      args:
        chdir: /home/ubuntu/{{git_repo}}
      
    - name: Prune everything
      community.docker.docker_prune:
        containers: true
        images: true